### ISSUE TITLE
Regexes are stateful

### ISSUE THREAD

**Issue by j201** [elm-lang/core#188] opened 2015-03-05 20:54 UTC
With Elm 0.14.1, running `find` on a regex changes its state, possibly causing future calls to `find` to act differently. It looks like this is because `find` uses JavaScript's `re.exec`, which sets the `lastIndex` property on the regex and makes it ignore matches before that index.

Example:

```elm
let re = regex "\\d"
    matchStr = foldl String.append "" << map .match
in [matchStr <| find (AtMost 1) re "1",
    matchStr <| find (AtMost 1) re "1",
    toString <| contains re "1",
    matchStr <| find (AtMost 1) re "1"]
```

Produces  
`["1","","True","1"]`

The first `find` probably sets `lastIndex` to 1, making it ignore the match in the second `find`. `contains` calls `str.match(re)`, which clears the regex state, making the last `find` work.

**Comment by evancz** [comment] 2015-03-06 17:30
I think there was a PR that fixes this. Can you take a look at the history of Regex.js to see?

**Comment by nathan** [comment] 2015-03-06 17:35
It looks like https://github.com/elm-lang/core/pull/156 fixed this.

**Comment by evancz** [comment] 2015-03-06 20:20
Cool, thanks for finding it @nathan! Let's close this until it can be reproduced with the latest version of the `Regex` library.

**Closed by evancz** 2015-03-06 20:20 UTC
