### ISSUE TITLE
json decoding: undefined is not a function

### ISSUE THREAD

**Issue by gpaul** [elm-lang/core#471] opened 2016-01-05 14:55 UTC
When parsing json into an algebraic datatype with Json.Decode.customDecoder and 'oneOf' I get the following error:
"expecting one of the following:\n    undefined is not a function\n    expecting a String but got {\"aaa\":\"1\"}"

The code follows:
```
import Graphics.Element exposing (show)
import Dict exposing (Dict)
import Json.Decode exposing ((:=), succeed, object2, list, string, bool, dict, int, maybe, decodeString, map, value, Decoder, customDecoder, oneOf)

jsonString = """{"aaa": "1"}"""

type V = Str String
            | Object (Dict String V)

stringer : String -> Result String V
stringer s = Ok (Str s)

stringer2 : Decoder V
stringer2 = customDecoder string stringer

objecter : Decoder (Dict String V)
objecter = dict decodeV

objecter2 : Decoder V
objecter2 = customDecoder objecter objecter3

objecter3 : (Dict String V) -> Result String V
objecter3 d = Ok (Object d)

decodeV = oneOf
    [
    objecter2
    , stringer2
    ]

main =
 case (decodeString decodeV jsonString) of
     Ok value -> show value
     Err msg -> show msg

```

**Comment by gpaul** [comment] 2016-01-05 15:09
The generated code looks like this. Could it be an order of initialization issue, where decodeV references objecter2, which references objecter, which references decodeV again?

```
   var Object = function (a) {
      return {ctor: "Object"
             ,_0: a};
   };
   var objecter3 = function (d) {
      return $Result.Ok(Object(d));
   };
   var Str = function (a) {
      return {ctor: "Str",_0: a};
   };
   var stringer = function (s) {
      return $Result.Ok(Str(s));
   };
   var stringer2 = A2($Json$Decode.customDecoder,
   $Json$Decode.string,
   stringer);
   var objecter2 = A2($Json$Decode.customDecoder,
   objecter,
   objecter3);
   var objecter = $Json$Decode.dict(decodeV);
   var decodeV = $Json$Decode.oneOf(_L.fromArray([objecter2
                                                 ,stringer2]));
```

**Comment by jvoigtlaender** [comment] 2016-01-05 15:35
See https://github.com/elm-lang/elm-compiler/issues/873 and the various issues occurring as links there that are related to `Json.Decode` specifically. For example, https://github.com/elm-lang/core/issues/361 and https://github.com/elm-lang/elm-compiler/issues/1244.

So yes, the cause here is the recursive dependencies. And it is well known that it is an issue that should be fixed. If you need a workaround as long as it is not yet fixed, I think the discussion in https://github.com/elm-lang/core/issues/361 (about introducing dummy arguments to delay evaluation) might help you.

**Comment by gpaul** [comment] 2016-01-06 08:25
Thanks, that works perfectly.

**Comment by awalterschulze** [comment] 2016-01-06 09:27
So for future reference:
objecter2 becomes
```
objecter2 : () -> Decoder V
objecter2 () = customDecoder objecter objecter3
```
And decodeV becomes
```
decodeV () = oneOf
    [
    objecter2 ()
    , stringer2
    ]
```
And main becomes
```
main =
 case (decodeString (decodeV ()) jsonString) of
     Ok value -> show value
     Err msg -> show msg
```
Is this correct?

**Comment by jvoigtlaender** [comment] 2016-01-06 09:37
Yes, plus a corresponding change to the use of `decodeV` in `objector`.

**Closed** 2016-01-06 09:37 UTC

**Comment by awalterschulze** [comment] 2016-01-06 09:46
Ah yes good catch
```
objecter : Decoder (Dict String V)
objecter = dict (decodeV ())
```
