### ISSUE TITLE
Graphics.show + Signal not working in Firefox

### ISSUE THREAD

**Issue by sporto** [elm-lang/core#427] opened 2015-10-20 22:17 UTC
This seems like a bug to me in Elm core.

http://share-elm.com/sprout/5626bc20e4b0966c193ddb6f

```
import Graphics.Element exposing (..)
import Keyboard
import Char

characters : Signal Char
characters =
  Signal.map Char.fromCode Keyboard.presses

main : Signal Element
main =
  Signal.map show characters
```

This works fine in Chrome, but in Firefox it only shows the initial value. Tested in Firefox 41.

**Comment by jvoigtlaender** [comment] 2015-10-21 06:16
I'm closing this as a duplicate of https://github.com/elm-lang/core/issues/326.

Please always look through existing issues first before opening a new one.

In this case, just using GitHub's issue search feature on the `core` repo with search phrase "Keyboard.presses" would have directly led you to the pre-existing issue.

**Closed by jvoigtlaender** 2015-10-21 06:16 UTC
