### ISSUE TITLE
No Error message when defining a type like this.

### ISSUE THREAD

**Issue by jackalcooper** [elm-lang/core#766] opened 2016-12-01 12:53 UTC
```elm
type Status
    = Success String
    | Http.Error
```

It did got compiled from Elm to Javascript but it fails when brunch trying to package it
```
Elm compile: Main.elm, in elm, to ../vendor/main.js
01 Dec 20:34:19 - error: Compiling of vendor/main.js failed. Line 16584: Unexpected token . 
01 Dec 20:34:19 - info: compiled 106 files into 2 files in 3.5 sec
```

**Comment by jvoigtlaender** [comment] 2016-12-01 13:14
Duplicate of https://github.com/elm-lang/elm-compiler/issues/1200.

**Closed by jvoigtlaender** 2016-12-01 13:14 UTC
