### ISSUE TITLE
Ports are not published in the specified order

### ISSUE THREAD

**Issue by DavidDTA** [elm-lang/core#730] opened 2016-10-13 17:30 UTC
When using a `Cmd.batch` to send data over two ports, the ports receive an event in the same order regardless of the order in which they appear in the batch.

Working example:
https://daviddta.github.io/elm-port-order-bug/

Code:
https://github.com/DavidDTA/elm-port-order-bug

Looking at the console, we see that port one always receives the event before port two.

**Comment by DavidDTA** [comment] 2016-10-13 17:31
In answer to the robot's questions, I'm using Chrome and Elm 0.17.1.

**Comment by jvoigtlaender** [comment] 2016-10-13 17:41
What makes you think this is a bug? Is there any documentation out there that claims any guarantees about the order of stuff happening that is put into `Cmd.batch`? (Hint: I don't think there is. And there should not be.)

If there is nothing like that to be found, then this is not a bug, but instead some feature you want (order preservation on stuff put into `Cmd.batch`). In that case, the issue tracker is not the appropriate venue for such a feature request. Such discussions happen on Slack or on the mailing list.

http://elm-lang.org/community

**Comment by DavidDTA** [comment] 2016-10-14 01:29
I tried posting to the elm discuss mailing list following your suggesion, but it has not gone through yet (pending approval).

**Comment by jvoigtlaender** [comment] 2016-10-14 04:16
Okay, I'm sure the message will get through on the mailing list, so am closing the issue here.

Meanwhile, maybe this helps you as well: http://faq.elm-community.org/17.html#what-is-the-difference-between-cmd-and-task

Note that it talks about multiset in relation to Cmd. Multisets have no order.

**Closed by jvoigtlaender** 2016-10-14 04:16 UTC

**Comment by DavidDTA** [comment] 2016-10-14 05:25
A few questions about the linked article:

1. The article claims that `Cmd` is not monadic, but I believe that the existence of `Cmd.Extra.message` and `Cmd.map` indicates that it is.
1. The article mentions that APIs generally expose `Task` in favor of `Cmd`.  Why is the port API `a -> Cmd msg` instead of  `a -> Task Never ()` or something like that?
1. Is there a recommended way to pass data to ports in order?  I've come up with the workaround of sending over only one port per update and using `Cmd.Extra.message` to trigger additional updates immediately, but I don't think it's very clean.

**Comment by jvoigtlaender** [comment] 2016-10-14 05:29
All these are good questions. For the mailing list.

But let me answer the first one quickly: For something to be monadic, you need not just (in Haskell terms) "something like `return`" and "something like `fmap`", which is what `Cmd.Extra.message` and `Cmd.map` are. You also need "something like `>>=`". And that's exactly what `Cmd` does not have. Thus it is not monadic. Maybe your understanding of "monadic" is wrong/incomplete.
