### ISSUE TITLE
Wrong type of the exponentiation (^) operator.

### ISSUE THREAD

**Issue by durkiewicz** [elm-lang/core#526] opened 2016-03-16 11:41 UTC
It is `number -> number -> number`, but I think it should be `number -> number -> Float` because you can get a non-integer even when you pass two integers to the function. The following code compiles without errors in Elm 0.16 (which is in my opinion wrong):
```
x : Int
x = 2 ^ -1
```

**Comment by jvoigtlaender** [comment] 2016-03-16 13:53
Duplicate of https://github.com/elm-lang/core/issues/194.

**Closed by jvoigtlaender** 2016-03-16 13:53 UTC
