### ISSUE TITLE
Date.fromString calls strongly discouraged Javascript code

### ISSUE THREAD

**Issue by mariosangiorgio** [elm-lang/core#701] opened 2016-08-27 19:54 UTC
I am working on some code that uses dates. When I looked at the documentation of `Date.fromString` I didn't find any indication about the format used so I had a look at the source code.

I figured out it used the [native Javascript Date](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Date). Reading the documentation on Mozilla's website I found this worrying note:

> parsing of date strings with the Date constructor (and Date.parse, they are equivalent) is strongly discouraged due to browser differences and inconsistencies.

Has anyone looked into what these inconsistencies are?

I think we should do one of the following things:

- investigate what the inconsistencies are and document them on the module documentation. Hardly ideal, but at least users are going to be aware of possible issues
- write a pure elm parser, with a well defined accepted format
- remove the function entirely

What do you think?

**Comment by evancz** [comment] 2016-08-29 23:22
This is a duplicate of #632, follow along there.

**Closed by evancz** 2016-08-29 23:22 UTC
