### ISSUE TITLE
Cannot read property 'ctor' of undefined

### ISSUE THREAD

**Issue by Hurtak** [elm-lang/core#680] opened 2016-08-07 18:00 UTC
The following code compiles and throws runtime error `Uncaught TypeError: Cannot read property 'ctor' of undefined`
It should not compile since I am referencing non-existing variable

Mimimal example code:
```elm
import Html exposing (text)

main =
    (List.foldl (\current aggregated -> 
        let
            newAggregated = 
                current :: newAggregated -- typo here, was supposed to be aggregated
        in
            newAggregated
    ) [] [1, 2, 3]) |> toString |> text
```

**Comment by evancz** [comment] 2016-08-07 18:34
This is a duplicate of https://github.com/elm-lang/elm-compiler/issues/873

**Closed by evancz** 2016-08-07 18:34 UTC
