### ISSUE TITLE
Crash when using an invalid regular expression

### ISSUE THREAD

**Issue by jonathanhefner** [elm-lang/core#157] opened 2015-02-03 14:32 UTC
Issue for discussion thread https://groups.google.com/d/topic/elm-discuss/7Uwl5-usqjs/discussion

Basically, JavaScript's `RegExp` (which is what Elm's `Regex` sits on top of) can throw an exception when given an invalid string.  Examples:
```javascript
RegExp("a"); // OK
RegExp("\\"); // Exception!
RegExp("("); // Exception!
RegExp("(?"); // Exception!
RegExp("(?:"); // Exception!
RegExp("?"); // Exception!
RegExp("+"); // Exception!
RegExp("*"); // Exception!
```

The obvious fix is to make Elm's `Regex.regex` return a `Result` (or a `Maybe`), but that seems like a pain to work with.  It's also an API-breaking change, which I have no problems with whatsoever, but others might.

The only other solution I can think of is to escape characters at the end of an input string until no exception is thrown.  For example:
```javascript
RegExp("(?:"); // Exception!
RegExp("(?\\:"); // Exception!
RegExp("(\\?\\:"); // Exception!
RegExp("\\(\\?\\:"); // OK
```

It's a bit hacky though, and may not follow the principle of least surprise.  Thoughts?

**Comment by Dobiasd** [comment] 2015-02-03 15:11
In my opinion the API-breaking change (with Result or Maybe) is the better solution.

**Comment by salutis** [comment] 2015-02-03 15:35
+1 for API-breaking changes. The best thing about Elm is that it's opinionated.

**Comment by rtfeldman** [comment] 2015-08-30 19:27
Duplicate of #378, which has further discussion.

**Comment by jvoigtlaender** [comment] 2015-08-30 19:34
Okay, closing this here as a duplicate.

**Closed by jvoigtlaender** 2015-08-30 19:34 UTC
