### ISSUE TITLE
Make Date comparable?

### ISSUE THREAD

**Issue by maxf** [elm-lang/core#851] opened 2017-04-06 12:54 UTC
It would be nice to be able to compare dates, eg.
```
Date.fromTime 100000000) < (Date.fromTime 2000000000000)
```
But currently Date isn't a comparable type, making it a bit complicated to do things like having dates as Dict keys or sorting Dates.

**Comment by jvoigtlaender** [comment] 2017-04-06 18:51
This is a duplicate of https://github.com/elm-lang/elm-compiler/issues/1482. @evancz

**Comment by lukewestby** [comment] 2017-05-17 15:18
I added to #816 as well. Since we're tracking there as well as in a compiler issue let's close this.

**Closed by lukewestby** 2017-05-17 15:18 UTC
