### ISSUE TITLE
runtime error in Json decoding

### ISSUE THREAD

**Issue by goertzenator** [elm-lang/core#704] opened 2016-08-30 14:49 UTC
I have a Json decoder that creates a JS runtime error when executed.  Note that `decodeOffsets` is factored out as a separate function:

``` Elm
decodeEeprom : Json.Decoder Eeprom
decodeEeprom =
    let
        createEeprom offsets subchannel_config channel_desc =
            { offsets = offsets,
              subchannel_config = subchannel_config,
              channel_desc = channel_desc
            }
        decodeOffsets           = "offsets" := decodeOffsets
        decodeSubchannel_config = "subchannel_config" := Json.list Json.int
        decodeChannel_desc      = "channel_desc" := Json.list Json.string
    in
        Json.object3 createEeprom decodeOffsets decodeSubchannel_config decodeChannel_desc

decodeOffsets = Json.list Json.float
```

The *incorrect* JS that is generated is...

``` javascript
var _user$project$Eeprom$decodeEeprom = function () {
	var decodeChannel_desc = A2(
		_elm_lang$core$Json_Decode_ops[':='],
		'channel_desc',
		_elm_lang$core$Json_Decode$list(_elm_lang$core$Json_Decode$string));
	var decodeSubchannel_config = A2(
		_elm_lang$core$Json_Decode_ops[':='],
		'subchannel_config',
		_elm_lang$core$Json_Decode$list(_elm_lang$core$Json_Decode$int));
	var decodeOffsets = A2(_elm_lang$core$Json_Decode_ops[':='], 'offsets', decodeOffsets); //<- decodeOffsets param is undefined!
	var createEeprom = F3(
		function (offsets, subchannel_config, channel_desc) {
			return {offsets: offsets, subchannel_config: subchannel_config, channel_desc: channel_desc};
		});
	return A4(_elm_lang$core$Json_Decode$object3, createEeprom, decodeOffsets, decodeSubchannel_config, decodeChannel_desc);
}();
```

In the above the `decodeOffsets` parameter to `decodeOffsets = A2(...`  I assume should actually be referring to this function:

``` javascript
var _user$project$Eeprom$decodeOffsets = _elm_lang$core$Json_Decode$list(_elm_lang$core$Json_Decode$float);
```

But it doesn't, and it eventually crashes. :(

This is on `elm-lang/core-4.0.5`.

**Comment by goertzenator** [comment] 2016-08-30 15:38
I've boiled this down to a much simpler example, and it may just be my misunderstanding of the language.  In `let y = y` I assume this to mean "Create a local variable named y with the same value as the module-scoped y."  But something else is clearly happening and instead of seeing the output `"123"` I see `"<internal structure>"`.

I'm leaving the Json case above in place because it manifests in a more serious javascript crash.

``` Elm
import Html exposing (text)

main =
  text (toString x)

x : Int
x =
    let
        --y = 123  -- this outputs "123"
        y = y     -- this outputs "<internal structure>"
    in
        y

y = 123  -- not needed in "y = y" case
```

**Comment by evancz** [comment] 2016-08-30 16:04
Duplicate of https://github.com/elm-lang/elm-compiler/issues/873

**Closed by evancz** 2016-08-30 16:04 UTC
